"""Core ChatGPT provider descriptor.

The ChatGPT engine used to receive this descriptor from the signed official
plugin's runtime generation. Since the plugin platform retirement (stage 2,
2026-10-02) it is core: the engine factory uses this constant, and
``validate_responses_descriptor`` still checks it on every engine build.
"""

from __future__ import annotations

from typing import Any

CORE_CHATGPT_PROVIDER_DESCRIPTOR: dict[str, Any] = {   'descriptor_schema_version': 5,
    'provider_id': 'chatgpt',
    'engine_type': 'chatgpt',
    'endpoint': 'https://chatgpt.com/backend-api/codex',
    'auth_profile': 'chatgpt_subscription_oauth',
    'headers': [   {'name': 'Authorization', 'value': 'Bearer {secret:access_token}'},
                   {'name': 'ChatGPT-Account-ID', 'value': '{auth:account_id}'},
                   {'name': 'originator', 'value': 'jenny'},
                   {'name': 'User-Agent', 'value': 'jenny'},
                   {'name': 'Accept', 'value': 'text/event-stream'},
                   {'name': 'Content-Type', 'value': 'application/json'}],
    'request_template': 'openai_responses_v1',
    'input_template': 'openai_responses_input_v1',
    'tool_template': 'openai_function_tools_v1',
    'lookup_tables': [   {   'name': 'reasoning_effort',
                             'entries': [   {'from': 'minimal', 'to': 'low'},
                                            {'from': 'low', 'to': 'low'},
                                            {'from': 'medium', 'to': 'medium'},
                                            {'from': 'high', 'to': 'high'},
                                            {'from': 'xhigh', 'to': 'xhigh'},
                                            {'from': 'max', 'to': 'max'}]}],
    'safe_scalar_rules': [   {   'name': 'error.code',
                                 'kind': 'string',
                                 'max_utf8_bytes': 64,
                                 'minimum': 0,
                                 'maximum': 0},
                             {   'name': 'error.message',
                                 'kind': 'string',
                                 'max_utf8_bytes': 512,
                                 'minimum': 0,
                                 'maximum': 0},
                             {   'name': 'rate_limit.reset_at',
                                 'kind': 'number',
                                 'max_utf8_bytes': 0,
                                 'minimum': 0,
                                 'maximum': 9007199254740991}],
    'error_map': [   {   'status_code': 401,
                         'provider_code': '',
                         'reason_code': 'authentication_required',
                         'retryable': False},
                     {   'status_code': 429,
                         'provider_code': '',
                         'reason_code': 'rate_limited',
                         'retryable': True},
                     {   'status_code': 500,
                         'provider_code': '',
                         'reason_code': 'provider_unavailable',
                         'retryable': True}],
    'stream_map': [   {   'event': 'response.output_text.delta',
                          'output_kind': 'text_delta',
                          'source_path': 'delta'},
                      {   'event': 'response.reasoning_summary_text.delta',
                          'output_kind': 'reasoning_delta',
                          'source_path': 'delta'},
                      {   'event': 'response.reasoning_text.delta',
                          'output_kind': 'reasoning_delta',
                          'source_path': 'delta'},
                      {   'event': 'response.output_item.done',
                          'output_kind': 'output_item',
                          'source_path': 'item'},
                      {   'event': 'response.completed',
                          'output_kind': 'completed',
                          'source_path': 'response'},
                      {   'event': 'response.failed',
                          'output_kind': 'failed',
                          'source_path': 'response.error'}],
    'model_catalog': [   {'id': 'gpt-6.1-sol', 'label': 'GPT-6.1 Sol', 'context_length': 272000},
                         {'id': 'gpt-6-sol', 'label': 'GPT-6 Sol', 'context_length': 272000},
                         {'id': 'gpt-6-luna', 'label': 'GPT-6 Luna', 'context_length': 272000},
                         {'id': 'gpt-5.6-sol', 'label': 'GPT-5.6 Sol', 'context_length': 272000},
                         {'id': 'gpt-6-astra', 'label': 'GPT-6 Astra', 'context_length': 272000},
                         {   'id': 'gpt-5.6-terra',
                             'label': 'GPT-5.6 Terra',
                             'context_length': 272000},
                         {'id': 'gpt-5.6-luna', 'label': 'GPT-5.6 Luna', 'context_length': 272000},
                         {   'id': 'gpt-5.3-codex-spark',
                             'label': 'GPT-5.3 Codex Spark',
                             'context_length': 128000},
                         {'id': 'gpt-5.5', 'label': 'GPT-5.5', 'context_length': 272000},
                         {'id': 'gpt-5.4', 'label': 'GPT-5.4', 'context_length': 272000},
                         {'id': 'gpt-5.4-mini', 'label': 'GPT-5.4 mini', 'context_length': 272000},
                         {'id': 'gpt-5.2', 'label': 'GPT-5.2', 'context_length': 272000}],
    'core_adapters': ['citation_marker_normalizer', 'reasoning_item_replay_cache']}
