"""Derive the Linux host runtime lock from existing pins and official PyPI hashes.

Run explicitly when promoting dependency pins. This does not choose newer
versions or install packages. Image builds consume the checked-in result.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[2]
EXCLUDED = {"altgraph", "macholib", "pefile", "pyinstaller",
            "pyinstaller-hooks-contrib", "pywin32-ctypes"}


def main() -> None:
    source = (ROOT / "requirements-lock.txt").read_text(encoding="utf-8")
    pins = re.findall(r"^([A-Za-z0-9_-]+)==([^ ;\\]+)", source, flags=re.MULTILINE)
    rows = ["# Linux amd64 CPython 3.11 host runtime; existing Jenny pins.",
            "# Generated by scripts/packaging/build_host_lock.py from official PyPI metadata.",
            "# No installer, model weights, GPU runtime, or optional execution dependencies."]
    for name, version in pins:
        if name.lower() in EXCLUDED:
            continue
        with urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as response:
            metadata = json.load(response)
        hashes = []
        for item in metadata["urls"]:
            filename = item["filename"]
            pure = filename.endswith("-none-any.whl")
            native = (filename.endswith(".whl") and "manylinux" in filename
                      and "x86_64" in filename
                      and ("cp311-" in filename or re.search(r"cp3(?:[6-9]|10)-abi3-", filename)))
            if not item.get("yanked") and (pure or native):
                hashes.append(item["digests"]["sha256"])
        if not hashes:
            raise RuntimeError(f"No compatible wheel for {name}=={version}")
        rows.append(f"{name}=={version} " + "\\")
        rows.append(" \\\n".join(f"    --hash=sha256:{value}" for value in sorted(set(hashes))))
    (ROOT / "server" / "requirements-lock.txt").write_text("\n".join(rows) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
