"""The answer and the compaction summary share one generation reservation (TR-006).

They are generated by different requests, so the budget holds back only the
larger of the two (each keeps its own cap) instead of their sum.
"""

from __future__ import annotations

import pytest

from sidecar.ai.context.compaction import _RETRY_REMINDER_MESSAGE
from sidecar.ai.context.compaction_prompts import (
    MAX_COMPACTION_SYSTEM_CONTEXT_CHARS,
    build_full_compaction_messages,
)
from sidecar.ai.context.compaction_window import summary_input_limit
from sidecar.ai.context.token_budget import (
    CharEstimationBackend,
    TokenBudget,
    estimate_messages_tokens,
)


class _ExactTokenizer(CharEstimationBackend):
    is_exact_match = True


def _summariser_prompt_tokens() -> int:
    """The summary request minus its history, at its largest.

    The same estimate compact_context admits against: the default prompt, the
    system context at its cap (plus the truncation marker), the conversation
    label and end instruction, and the one retry reminder.
    """
    messages = build_full_compaction_messages(
        [], system_context="s" * (MAX_COMPACTION_SYSTEM_CONTEXT_CHARS + 1)
    )
    return estimate_messages_tokens([*messages, _RETRY_REMINDER_MESSAGE])


def test_64k_window_with_42_measured_tools_compacts_near_33_7k() -> None:
    budget = TokenBudget(
        context_window=65_536, max_output_tokens=16_384, tool_overhead_per_tool=278
    )
    assert budget.summary_reservation() == 8_192
    assert budget.effective_context(42) == 65_536 - 16_384 - 42 * 278 == 37_476
    assert budget.auto_compact_threshold(42) == 33_728  # was 26,355 with the sum


def test_small_window_uses_the_minimum_caps() -> None:
    # 8k: output capped at a quarter (2,048), summary at its 1,024 floor.
    budget = TokenBudget(context_window=8_192, max_output_tokens=8_192)
    assert budget.summary_reservation() == 1_024
    assert budget.effective_context(0) == 8_192 - 2_048 == 6_144

    # 4k with a small answer allowance: the 1,024 summary floor is the larger.
    tiny = TokenBudget(context_window=4_096, max_output_tokens=512)
    assert tiny.summary_reservation() == 1_024  # window // 8 is only 512
    assert tiny.effective_context(0) == 4_096 - 1_024 == 3_072


def test_summary_reservation_wins_when_larger_than_the_output() -> None:
    budget = TokenBudget(context_window=65_536, max_output_tokens=2_048)
    assert budget.summary_reservation() == 8_192
    assert budget.effective_context(10) == 65_536 - 8_192 - 10 * 500
    # A configured summary share still keeps the eighth-of-window cap.
    capped = TokenBudget(
        context_window=65_536, max_output_tokens=2_048, reserved_for_summary=20_000
    )
    assert capped.summary_reservation() == 65_536 // 8
    assert capped.effective_context(0) == 65_536 - 8_192


def test_the_answer_request_still_fits_at_the_error_threshold() -> None:
    budget = TokenBudget(context_window=65_536, max_output_tokens=16_384)
    # history + tool schemas + the full output reservation <= window
    assert budget.error_threshold(42) + budget.tool_overhead(42) <= budget.hard_prompt_limit()


@pytest.mark.parametrize(
    ("context_window", "max_output_tokens", "num_tools", "per_tool"),
    [
        (8_192, 8_192, 0, 500),
        (16_384, 16_384, 0, 500),
        (32_768, 8_192, 24, 500),
        (65_536, 16_384, 42, 278),  # the dogfood window
        (65_536, 2_048, 0, 500),  # summary reservation larger than the output
        (131_072, 16_384, 0, 500),
        (200_000, 16_384, 46, 500),
    ],
)
def test_summary_request_fits_the_window_at_the_new_thresholds(
    context_window: int, max_output_tokens: int, num_tools: int, per_tool: int
) -> None:
    """history + summariser prompt + summary share <= window, for the most
    history the loop carries before its hard stop (the error threshold)."""
    budget = TokenBudget(
        context_window=context_window,
        max_output_tokens=max_output_tokens,
        tool_overhead_per_tool=per_tool,
    )
    history = budget.error_threshold(num_tools)
    prompt = _summariser_prompt_tokens()
    assert prompt < 1_200

    assert history + prompt + budget.summary_reservation() <= context_window


@pytest.mark.parametrize(
    ("context_window", "max_output_tokens", "num_tools", "per_tool"),
    [(32_768, 8_192, 24, 500), (65_536, 16_384, 42, 278), (200_000, 16_384, 46, 500)],
)
def test_summariser_admits_the_whole_history_at_the_threshold(
    context_window: int, max_output_tokens: int, num_tools: int, per_tool: int
) -> None:
    # On 32k and larger windows the summariser input limit (which reserves the
    # full configured summary allowance) still takes every row counted by an
    # exact tokenizer, so the higher trigger does not make the summary drop
    # history. A non-exact estimate is admitted under a margin (HB-028) and
    # may drop the oldest rows behind an omission marker instead.
    budget = TokenBudget(
        context_window=context_window,
        max_output_tokens=max_output_tokens,
        tool_overhead_per_tool=per_tool,
    )
    limit = summary_input_limit(
        budget, prompt_tokens=_summariser_prompt_tokens(), backend=_ExactTokenizer()
    )
    assert limit >= budget.error_threshold(num_tools)
